apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-chatbot-config
  namespace: ai-chatbot
data:
  GEMINI_MODEL: gemini-3.6-flash
  CLIENT_URL: http://ai-chatbot-frontend
  POSTGRES_DB: ai_chatbot
  POSTGRES_USER: postgres
