apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot-postgres
  namespace: ai-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chatbot-postgres
  template:
    metadata:
      labels:
        app: ai-chatbot-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ai-chatbot-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: ai-chatbot-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ai-chatbot-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d ai_chatbot"]
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
