apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot-postgres
  namespace: ai-chatbot
spec:
  selector:
    app: ai-chatbot-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
